Fix: issue with acion not concluding

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,7 +21,9 @@ jobs:
       - name: ALU
         run: |
           iverilog -o alu -g2005-sv src/alu.sv tests/alu_tb.sv
-          vvp alu
+          if ! vvp alu; then
+            exit 1  # Terminate the job if vvp alu fails
+          fi
 
       - name: Controller
         run: |
